server:
  port: 8888
#Elasticsearch配置
elasticsearch:
  host: 127.0.0.1
  port: 9300
  # 需要修改 elasticsearch 安装目录下config/elasticsearch.yml 的cluster.name的值，默认值为 elasticsearch
  clustername: my-application
  search:
    pool:
      size: 5